import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Land from "./components/land"
import Second from "./components/second"
import Third from './components/third'
import Fourth from './components/fourth'
import Fifth from './components/fifth'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>iPhone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Land />
        <Second />
        <Third />
        <Fourth />
        <Fifth />
        <p>Copyright © 2023. Sarasani Manaswini, All rights reserved.</p>
      </main> 
    </>
  )
}
